---
name: 'Pull Request - Compile Build'

defaults:
  run:
    shell: bash

concurrency:
  group: ${{ github.head_ref }}${{ github.ref }}
  cancel-in-progress: true

env:
  JAVA_VERSION: 17
  ATALA_GITHUB_ACTOR: ${{ secrets.ATALA_GITHUB_ACTOR }}
  ATALA_GITHUB_TOKEN: ${{ secrets.ATALA_GITHUB_TOKEN }}

on: [pull_request]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: "Checkout the repo"
        uses: actions/checkout@v3

      - name: "Install Java ${{ env.JAVA_VERSION }}"
        uses: actions/setup-java@v3
        with:
          java-version: "${{ env.JAVA_VERSION }}"
          distribution: zulu

      - name: "Gradle Build Action"
        uses: gradle/gradle-build-action@v2

      - name: "Install Homebrew"
        run: >
          /bin/bash -c "$(curl -fsSL
          https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

      - name: "Install autoconf, automake, libtool"
        run: |
          brew install autoconf automake libtool

      - name: "Install Mac ToolChain"
        run: |
          brew tap messense/macos-cross-toolchains

      - name: "Install Linux GNU for x86_64"
        run: |
          rm '/usr/local/bin/2to3' || true
          rm '/usr/local/bin/2to3-3.11' || true
          rm '/usr/local/bin/2to3-3.12' || true
          rm '/usr/local/bin/python3' || true
          rm '/usr/local/bin/python3.11' || true
          rm '/usr/local/bin/python3.12' || true
          rm '/usr/local/bin/idle3' || true
          rm '/usr/local/bin/idle3.11' || true
          rm '/usr/local/bin/idle3.12' || true
          rm '/usr/local/bin/pydoc3' || true
          rm '/usr/local/bin/pydoc3.11' || true
          rm '/usr/local/bin/pydoc3.12' || true
          rm '/usr/local/bin/python3-config' || true
          rm '/usr/local/bin/python3.11-config' || true
          rm '/usr/local/bin/python3.12-config' || true
          rm -r '/usr/local/lib/node_modules' || true
          brew install --overwrite x86_64-unknown-linux-gnu

      - name: "Install Linux GNU for aarch64"
        run: |
          brew install --overwrite aarch64-unknown-linux-gnu

      - name: "Install Rust Targets"
        run: |
          rustup target add armv7-linux-androideabi
          rustup target add i686-linux-android
          rustup target add aarch64-linux-android
          rustup target add x86_64-linux-android
          rustup target add aarch64-apple-darwin
          rustup target add x86_64-apple-darwin
          rustup target add aarch64-unknown-linux-gnu
          rustup target add x86_64-unknown-linux-gnu

      - name: "Install Rust Cargo NDK"
        run: |
          cargo install cargo-ndk

      - name: "Build Check"
        working-directory: ./sd-jwt-kmp
        run: ./gradlew :build
